onlyBuiltDependencies:
  - esbuild

overrides:
  cookie@<0.7.0: '>=0.7.0'
  esbuild@<=0.24.2: '>=0.25.0'
  form-data@<2.5.4: '>=2.5.4'
  postcss@<7.0.36: '>=7.0.36'
  postcss@<8.4.31: '>=8.4.31'
  qs@<6.14.1: '>=6.14.1'
  svelte@<4.2.19: '>=4.2.19'
  tough-cookie@<4.1.3: '>=4.1.3'
